// <auto-generated />
using System;
using Masa.Dcc.Infrastructure.EFCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Masa.Dcc.Infrastructure.EFCore.SqlServer.Migrations
{
    [DbContext(typeof(DccDbContext))]
    partial class DccDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Masa.Dcc.Infrastructure.Domain.Shared.AppConfigObject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AppId")
                        .HasColumnType("int")
                        .HasComment("AppId");

                    b.Property<int>("ConfigObjectId")
                        .HasColumnType("int")
                        .HasComment("ConfigObjectId");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("Creator")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("EnvironmentClusterId")
                        .HasColumnType("int")
                        .HasComment("EnvironmentClusterId");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModificationTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("Modifier")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ConfigObjectId")
                        .IsUnique();

                    b.ToTable("AppConfigObjects");
                });

            modelBuilder.Entity("Masa.Dcc.Infrastructure.Domain.Shared.AppPin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AppId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("Creator")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModificationTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("Modifier")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("AppPin");
                });

            modelBuilder.Entity("Masa.Dcc.Infrastructure.Domain.Shared.AppSecret", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AppId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("Creator")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EncryptionSecret")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("EnvironmentId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModificationTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("Modifier")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("Secret")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("AppSecrets");
                });

            modelBuilder.Entity("Masa.Dcc.Infrastructure.Domain.Shared.BizConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("Creator")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Identity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModificationTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("Modifier")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BizConfigs");
                });

            modelBuilder.Entity("Masa.Dcc.Infrastructure.Domain.Shared.BizConfigObject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BizConfigId")
                        .HasColumnType("int");

                    b.Property<int>("ConfigObjectId")
                        .HasColumnType("int")
                        .HasComment("ConfigObjectId");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("Creator")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("EnvironmentClusterId")
                        .HasColumnType("int")
                        .HasComment("EnvironmentClusterId");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModificationTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("Modifier")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("BizConfigId");

                    b.HasIndex("ConfigObjectId")
                        .IsUnique();

                    b.ToTable("BizConfigObjects");
                });

            modelBuilder.Entity("Masa.Dcc.Infrastructure.Domain.Shared.ConfigObject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("ntext");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("Creator")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Encryption")
                        .HasColumnType("bit");

                    b.Property<string>("FormatLabelCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("Format");

                    b.Property<bool>("FromRelation")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModificationTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("Modifier")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("Name");

                    b.Property<int>("RelationConfigObjectId")
                        .HasColumnType("int")
                        .HasComment("Relation config object Id");

                    b.Property<string>("TempContent")
                        .IsRequired()
                        .HasColumnType("ntext");

                    b.Property<int>("Type")
                        .HasColumnType("int")
                        .HasComment("Type");

                    b.HasKey("Id");

                    b.ToTable("ConfigObjects");
                });

            modelBuilder.Entity("Masa.Dcc.Infrastructure.Domain.Shared.ConfigObjectRelease", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasComment("Comment");

                    b.Property<int>("ConfigObjectId")
                        .HasColumnType("int")
                        .HasComment("Config object Id");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(2147483647)
                        .HasColumnType("ntext")
                        .HasComment("Content");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("Creator")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("FromReleaseId")
                        .HasColumnType("int")
                        .HasComment("Rollback From Release Id");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsInvalid")
                        .HasColumnType("bit")
                        .HasComment("If it is rolled back, it will be true");

                    b.Property<DateTime>("ModificationTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("Modifier")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("Name");

                    b.Property<byte>("Type")
                        .HasColumnType("tinyint")
                        .HasComment("Release type");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("varchar(20)")
                        .HasComment("Version format is yyyyMMddHHmmss");

                    b.HasKey("Id");

                    b.HasIndex("ConfigObjectId");

                    b.ToTable("ConfigObjectReleases");
                });

            modelBuilder.Entity("Masa.Dcc.Infrastructure.Domain.Shared.Label", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("Code");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("Creator")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasComment("Description");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModificationTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("Modifier")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasComment("Name");

                    b.Property<string>("TypeCode")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasComment("TypeCode");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasComment("TypeName");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "TypeCode", "IsDeleted" }, "IX_TypeCode");

                    b.ToTable("Labels");
                });

            modelBuilder.Entity("Masa.Dcc.Infrastructure.Domain.Shared.PublicConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("Creator")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Identity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModificationTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("Modifier")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("PublicConfigs");
                });

            modelBuilder.Entity("Masa.Dcc.Infrastructure.Domain.Shared.PublicConfigObject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ConfigObjectId")
                        .HasColumnType("int")
                        .HasComment("ConfigObjectId");

                    b.Property<DateTime>("CreationTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("Creator")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("EnvironmentClusterId")
                        .HasColumnType("int")
                        .HasComment("EnvironmentClusterId");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("ModificationTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("Modifier")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("PublicConfigId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ConfigObjectId")
                        .IsUnique();

                    b.HasIndex("PublicConfigId");

                    b.ToTable("PublicConfigObjects");
                });

            modelBuilder.Entity("Masa.Dcc.Infrastructure.Domain.Shared.AppConfigObject", b =>
                {
                    b.HasOne("Masa.Dcc.Infrastructure.Domain.Shared.ConfigObject", "ConfigObject")
                        .WithOne("AppConfigObject")
                        .HasForeignKey("Masa.Dcc.Infrastructure.Domain.Shared.AppConfigObject", "ConfigObjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ConfigObject");
                });

            modelBuilder.Entity("Masa.Dcc.Infrastructure.Domain.Shared.BizConfigObject", b =>
                {
                    b.HasOne("Masa.Dcc.Infrastructure.Domain.Shared.BizConfig", "BizConfig")
                        .WithMany("BizConfigObjects")
                        .HasForeignKey("BizConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Masa.Dcc.Infrastructure.Domain.Shared.ConfigObject", "ConfigObject")
                        .WithOne("BizConfigObject")
                        .HasForeignKey("Masa.Dcc.Infrastructure.Domain.Shared.BizConfigObject", "ConfigObjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BizConfig");

                    b.Navigation("ConfigObject");
                });

            modelBuilder.Entity("Masa.Dcc.Infrastructure.Domain.Shared.ConfigObjectRelease", b =>
                {
                    b.HasOne("Masa.Dcc.Infrastructure.Domain.Shared.ConfigObject", null)
                        .WithMany("ConfigObjectRelease")
                        .HasForeignKey("ConfigObjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Masa.Dcc.Infrastructure.Domain.Shared.PublicConfigObject", b =>
                {
                    b.HasOne("Masa.Dcc.Infrastructure.Domain.Shared.ConfigObject", "ConfigObject")
                        .WithOne("PublicConfigObject")
                        .HasForeignKey("Masa.Dcc.Infrastructure.Domain.Shared.PublicConfigObject", "ConfigObjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Masa.Dcc.Infrastructure.Domain.Shared.PublicConfig", "PublicConfig")
                        .WithMany("PublicConfigObjects")
                        .HasForeignKey("PublicConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ConfigObject");

                    b.Navigation("PublicConfig");
                });

            modelBuilder.Entity("Masa.Dcc.Infrastructure.Domain.Shared.BizConfig", b =>
                {
                    b.Navigation("BizConfigObjects");
                });

            modelBuilder.Entity("Masa.Dcc.Infrastructure.Domain.Shared.ConfigObject", b =>
                {
                    b.Navigation("AppConfigObject")
                        .IsRequired();

                    b.Navigation("BizConfigObject")
                        .IsRequired();

                    b.Navigation("ConfigObjectRelease");

                    b.Navigation("PublicConfigObject")
                        .IsRequired();
                });

            modelBuilder.Entity("Masa.Dcc.Infrastructure.Domain.Shared.PublicConfig", b =>
                {
                    b.Navigation("PublicConfigObjects");
                });
#pragma warning restore 612, 618
        }
    }
}
